/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyect;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import org.scilab.forge.jlatexmath.*;
/**
 *
 * @author brayan
 */
public class JFrameLevel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameLevel.class.getName());
    private Main main;
    private Challenge challengeShow;
    private JFramePassChallenger framePassChallenger;
    /**
     * Creates new form JFrameLevel
     */
    public JFrameLevel() {
        initComponents();
        //this.setExtendedState(this.MAXIMIZED_BOTH);
    }
    
    public void cMain (Main main){
        this.main = main;
    }
    
    
    private void mostrarFormulaEnLabel(String form) {
        TeXFormula formula = new TeXFormula(form);
        TeXIcon icon = formula.createTeXIcon(TeXConstants.STYLE_DISPLAY, 20);

        JLabel labelLatex = new JLabel(icon);
        //labelLatex.setBackground(Color.BLACK);
        labelLatex.setOpaque(true);

        jLabelDescription.getParent().add(labelLatex);
        labelLatex.setBounds(jLabelDescription.getX(), jLabelDescription.getY() + 50, 600, 200);
}
    
    public  void printChallenge(){
        challengeShow = main.runGame();
        if(challengeShow != null){
            
           // mostrarFormulaEnLabel(challengeShow.getEnunciado());
            jLabelDescription.setText(challengeShow.getEnunciado());
            String[] temp = challengeShow.getOpciones();
            
            jLabelOptionA.setText(temp[0]);
            jLabelOptionB.setText(temp[1]);
            jLabelOptionC.setText(temp[2]);
            jLabelOptionD.setText(temp[3]);
        
            String[] dataGame = main.dataGame();
            String namePlayer,challengerPass;
            int livePlayer;
            livePlayer = Integer.parseInt(dataGame[0]);
            namePlayer = dataGame[1];
            challengerPass  = dataGame[2];
            ImageIcon icon;
            switch (Integer.parseInt(dataGame[3])){
                case 1: 
                    icon = new ImageIcon("src/imagenes/induccion_matematica.png");
                    jLabelImg.setIcon(icon);
                    break;
                
                case 2:
                    icon = new ImageIcon("src/imagenes/induccion_matematica.png");
                    jLabelImg.setIcon(icon);
                    break;
            }
        
            for (int index = 0; index < livePlayer; index++){
                jLabelLivesPlayer.setText(jLabelLivesPlayer.getText() + "\u2764" );
                
            }
        
            jLabelNamePlayer.setText(namePlayer); 
            jLabelChallenger.setText(challengerPass);
        }else{
            Start gameOver = new Start();
            gameOver.cMain(main);
            this.setVisible(false);
            gameOver.GameOver();
            gameOver.setVisible(true);

        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelDescription = new javax.swing.JLabel();
        jLabelOptionA = new javax.swing.JLabel();
        jButtonSend = new javax.swing.JButton();
        jLabelOptionB = new javax.swing.JLabel();
        jLabelOptionC = new javax.swing.JLabel();
        jLabelOptionD = new javax.swing.JLabel();
        jLabelNamePlayer = new javax.swing.JLabel();
        jLabelLivesPlayer = new javax.swing.JLabel();
        jLabelChallenger = new javax.swing.JLabel();
        jComboAnswer = new javax.swing.JComboBox<>();
        jLabelImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(121, 217, 238));
        jPanel1.setMaximumSize(new java.awt.Dimension(700, 530));

        jLabelDescription.setText(".");
        jLabelDescription.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelOptionA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelOptionA.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelOptionA.setText("jLabel2");

        jButtonSend.setText("Enviar");
        jButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendActionPerformed(evt);
            }
        });

        jLabelOptionB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelOptionB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelOptionB.setText("jLabel1");

        jLabelOptionC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelOptionC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelOptionC.setText("jLabel1");

        jLabelOptionD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelOptionD.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelOptionD.setText("jLabel1");

        jLabelNamePlayer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelNamePlayer.setText(".");

        jLabelLivesPlayer.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N

        jLabelChallenger.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelChallenger.setText(".");

        jComboAnswer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "a", "b", "c", "d" }));
        jComboAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboAnswerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOptionD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelNamePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                                .addComponent(jLabelLivesPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(jLabelChallenger, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSend)
                        .addGap(64, 64, 64))
                    .addComponent(jLabelDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOptionB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelOptionA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelOptionC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelLivesPlayer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                        .addComponent(jLabelChallenger, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jLabelNamePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabelOptionA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelOptionB)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelOptionC, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelOptionD, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSend)
                    .addComponent(jComboAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendActionPerformed
        // TODO add your handling code here:
        String answer =  jComboAnswer.getSelectedItem().toString();
        boolean pastChallenge = main.answer(answer);
        
        
        
        framePassChallenger = new JFramePassChallenger();
        framePassChallenger.cMain(main);
        framePassChallenger.printAnswer(pastChallenge);
        this.setVisible(false);
        framePassChallenger.setVisible(true);
        
       

        
        
        
    }//GEN-LAST:event_jButtonSendActionPerformed

    private void jComboAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboAnswerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameLevel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonSend;
    private javax.swing.JComboBox<String> jComboAnswer;
    private javax.swing.JLabel jLabelChallenger;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelImg;
    private javax.swing.JLabel jLabelLivesPlayer;
    private javax.swing.JLabel jLabelNamePlayer;
    private javax.swing.JLabel jLabelOptionA;
    private javax.swing.JLabel jLabelOptionB;
    private javax.swing.JLabel jLabelOptionC;
    private javax.swing.JLabel jLabelOptionD;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
