/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyect;

import java.awt.*;
import javax.swing.*;
/**
 *
 * @author brayan
 */
public class Start extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Start.class.getName());
    private Create_player createPlayer; 
    private Main main = new Main();
    
    /**
     * Creates new form NewJFrame1
     */
    public Start() {
        initComponents();
       // this.setExtendedState(MAXIMIZED_BOTH);
       // setAnimatedBackground(); 
       // jPanel1.setOpaque(false);  

                
    }
     
    public void cMain (Main main){
        this.main = main;
    }
    
    public void GameOver(){
        jLabelGameOver.setText("Te quedaste sin vidas, ¿quieres volver a jugar? ");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelGameOver = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setExtendedState(6);
        setPreferredSize(new java.awt.Dimension(700, 530));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelGameOver.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabelGameOver.setForeground(new java.awt.Color(153, 255, 255));
        jLabelGameOver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGameOver.setText("<html>PREPARATE <p>  PARA JUGAR <html>");
        jLabelGameOver.setToolTipText("");
        jLabelGameOver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelGameOver.setPreferredSize(new java.awt.Dimension(750, 530));
        jPanel1.add(jLabelGameOver, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 270, 120));
        jLabelGameOver.getAccessibleContext().setAccessibleName(""); // NOI18N

        jButton1.setBackground(new java.awt.Color(23, 23, 37));
        jButton1.setFont(new java.awt.Font("Viner Hand ITC", 0, 48)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 255, 255));
        jButton1.setText("JUGAR");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 204), 4));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 268, 108));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo_start.gif"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(700, 530));
        jLabel2.setMinimumSize(new java.awt.Dimension(700, 530));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 530));

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        main.createNewGame();
        this.setVisible(false);
        createPlayer = new Create_player();
        createPlayer.cMain(main);
        createPlayer.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Start().setVisible(true));
        
    }
    
    private void setAnimatedBackground() {
        java.net.URL url = getClass().getResource("/images/fondo_start_2.gif");

        if (url == null) {
            System.out.println("⚠️ No se encontró el fondo: /images/fondo_start_2.gif");
            return;
        }

        // Crear el JLabel con el GIF (sin escalar)
        JLabel fondoGif = new JLabel(new ImageIcon(url));
        fondoGif.setBounds(0, 0, getWidth(), getHeight());
        fondoGif.setOpaque(false);

        // Asegurar layout absoluto para controlar posición
        setLayout(null);

        // Agregar al fondo
        getLayeredPane().add(fondoGif, JLayeredPane.DEFAULT_LAYER - 1);

        // Ajustar tamaño cuando se redimensione
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                fondoGif.setBounds(0, 0, getWidth(), getHeight());
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelGameOver;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}


