/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyect;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author brayan
 */
public class JFrameLevel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameLevel.class.getName());
    private Main main;
    private Challenge challengeShow;
    private JFramePassChallenger framePassChallenger;
    /**
     * Creates new form JFrameLevel
     */
    public JFrameLevel() {
        initComponents();
        //this.setExtendedState(this.MAXIMIZED_BOTH);
    }
    
    public void cMain (Main main){
        this.main = main;
    }
    
    private void setScaledImage(Challenge challengeShow, JLabel label) {
        String ruta = challengeShow.getEnunciado(); // ejemplo: "/images/RETO_1_NIVEL_1_ENUNCUADO.png"
        java.net.URL url = getClass().getResource(ruta);

        if (url == null) {
            System.out.println("No se encontró la imagen en: " + ruta);
            return;
        }

        ImageIcon icon = new ImageIcon(url);
        Image img = icon.getImage();

        int labelWidth = label.getWidth();
        int labelHeight = label.getHeight();

        if (labelWidth > 0 && labelHeight > 0) {
            int imgWidth = icon.getIconWidth();
            int imgHeight = icon.getIconHeight();

            // Escala proporcional
            double escalaX = (double) labelWidth / imgWidth;
            double escalaY = (double) labelHeight / imgHeight;
            double escala = Math.min(escalaX, escalaY);

            int nuevoAncho = (int) (imgWidth * escala);
            int nuevoAlto = (int) (imgHeight * escala);

            Image imgEscalada = img.getScaledInstance(nuevoAncho, nuevoAlto, Image.SCALE_SMOOTH);
            label.setIcon(new ImageIcon(imgEscalada));
        }
    }
    
    public  void printChallenge(){
        challengeShow = main.runGame();
        if(challengeShow != null){
            //jLabelDescription.setText(challengeShow.getEnunciado());
            setScaledImage(challengeShow, jLabelDescription);
            
            jLabelDescription.addComponentListener(new java.awt.event.ComponentAdapter() {
                @Override
                public void componentResized(java.awt.event.ComponentEvent evt) {
                    setScaledImage(challengeShow, jLabelDescription);
                }
            });



            
            String[] temp = challengeShow.getOpciones();
            
            jLabelOptionA.setText(temp[0]);
            jLabelOptionB.setText(temp[1]);
            jLabelOptionC.setText(temp[2]);
            jLabelOptionD.setText(temp[3]);
        
            String[] dataGame = main.dataGame();
            String namePlayer,challengerPass;
            int livePlayer;
            livePlayer = Integer.parseInt(dataGame[0]);
            namePlayer = dataGame[1];
            challengerPass  = dataGame[2];
        
            for (int index = 0; index < livePlayer; index++){
                jLabelLivesPlayer.setText(jLabelLivesPlayer.getText() + "\u2764" );
            }
        
            jLabelNamePlayer.setText(namePlayer); 
            jLabelChallenger.setText(challengerPass);
        }else{
            Start gameOver = new Start();
            gameOver.cMain(main);
            this.setVisible(false);
            gameOver.GameOver();
            gameOver.setVisible(true);

        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelDescription = new javax.swing.JLabel();
        jLabelOptionA = new javax.swing.JLabel();
        jTextFieldAnswer = new javax.swing.JTextField();
        jButtonSend = new javax.swing.JButton();
        jLabelOptionB = new javax.swing.JLabel();
        jLabelOptionC = new javax.swing.JLabel();
        jLabelOptionD = new javax.swing.JLabel();
        jLabelNamePlayer = new javax.swing.JLabel();
        jLabelLivesPlayer = new javax.swing.JLabel();
        jLabelChallenger = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(700, 530));

        jLabelDescription.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelOptionA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOptionA.setText("jLabel2");

        jTextFieldAnswer.setText("jTextField1");

        jButtonSend.setText("Enviar");
        jButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendActionPerformed(evt);
            }
        });

        jLabelOptionB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOptionB.setText("jLabel1");

        jLabelOptionC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOptionC.setText("jLabel1");

        jLabelOptionD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOptionD.setText("jLabel1");

        jLabelNamePlayer.setText(".");

        jLabelChallenger.setText(".");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                        .addComponent(jButtonSend)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelOptionD, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelOptionB, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelOptionA, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelLivesPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(jLabelChallenger, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addComponent(jLabelDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNamePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelOptionC, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNamePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLivesPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelChallenger))
                        .addGap(12, 12, 12)
                        .addComponent(jLabelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addComponent(jLabelOptionA)
                .addGap(18, 18, 18)
                .addComponent(jLabelOptionB)
                .addGap(18, 18, 18)
                .addComponent(jLabelOptionC, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelOptionD, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSend))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendActionPerformed
        // TODO add your handling code here:
        String answer =  jTextFieldAnswer.getText();
        boolean pastChallenge = main.answer(answer);
        
        
        
        framePassChallenger = new JFramePassChallenger();
        framePassChallenger.cMain(main);
        framePassChallenger.printAnswer(pastChallenge);
        this.setVisible(false);
        framePassChallenger.setVisible(true);
        
       

        
        
        
    }//GEN-LAST:event_jButtonSendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameLevel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSend;
    private javax.swing.JLabel jLabelChallenger;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelLivesPlayer;
    private javax.swing.JLabel jLabelNamePlayer;
    private javax.swing.JLabel jLabelOptionA;
    private javax.swing.JLabel jLabelOptionB;
    private javax.swing.JLabel jLabelOptionC;
    private javax.swing.JLabel jLabelOptionD;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldAnswer;
    // End of variables declaration//GEN-END:variables
}
